language: c
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo pip install cpp-coveralls
install:
  - cmake -DENABLE_GCOV:BOOL=ON .
  - make
# command to run tests
script: ctest
# Submit to coveralls for coverage statistics
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
