language: c
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
install:
  - cmake .
  - make
# command to run tests
script: ctest -VV
